name: Deploy to EC2
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build client (Vite)
      - name: Install client deps
        run: npm ci --prefix client

      - name: Build client
        run: npm run build --prefix client

      # Package artifacts to ship
      - name: Tar client build
        run: tar -C client -czf client-dist.tar.gz dist

      - name: Tar server code (exclude node_modules)
        run: tar --exclude='server/node_modules' -czf server.tar.gz server

      # ---- COPY TO EC2 ----
      - name: Copy artifacts to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "client-dist.tar.gz,server.tar.gz"
          target: "/var/www/contact"

      # ---- DEPLOY ON EC2 ----
      - name: SSH deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /var/www/contact

            # Unpack client to client-dist/
            rm -rf client-dist && mkdir -p client-dist
            tar -xzf client-dist.tar.gz -C client-dist --strip-components=1

            # Unpack server to server/
            rm -rf server && mkdir -p server
            tar -xzf server.tar.gz

            # Ensure .env exists
            if [ ! -f server/.env ]; then
              echo "PORT=4000" > server/.env
              echo "DATABASE_URL=${{ secrets.DB_URL }}" >> server/.env
            fi

            # Install deps & migrate DB
            npm ci --prefix server || npm install --prefix server
            npm run migrate --prefix server

            # Start/Restart API
            if pm2 status contact-api >/dev/null 2>&1; then
              pm2 restart contact-api
            else
              pm2 start "npm start" --name contact-api --cwd /var/www/contact/server
              pm2 save
            fi

            # Reload Nginx
            sudo nginx -t && sudo systemctl reload nginx
